export { Hero } from './Hero'
export { About } from './About'
export { Experience } from './Experience'
export { Skills } from './Skills'
export { Projects } from './Projects'
export { Objectifs } from './Objectifs'
export { Contact } from './Contact'
export { Gallery } from './Gallery'
